["schedule"]
template = "template-planning-schedule"

["overview"]
generic = "generic-classic-document"

  ["overview".body]
  doc-title = "Documento de especificación de cronograma"
  ["overview".composition]
  content = "content-schedule-overview"
