["schedule.mpp"]
template = "template-planning-schedule"

["overview"]
template = "template-blank-document"

  ["overview".body]
  doc-title = "Documento de especificación de cronograma"
  content = "content:schedule-overview"
