["CHANGELOG"]
template = "template-changelog"

["endpoints"]
template = "template-blank-document"

  ["endpoints".body]
  doc-title = "Listado de servicios web, sockets y notificaciones"
  content = "content:sofware-endpoints"

["process"]
template = "template-sofware-process"

["sequence"]
template = "template-sofware-sequence"
