["charter"]
generic = "generic-classic-document"

  ["charter".body]
  doc-title = "Documento de Alcance"
  ["charter".composition]
  content = "content-planning-charter"

["requirements.<scope>"]
generic = "generic-classic-document"

  ["requirements.<scope>".body]
  doc-title = "Documento de historias de usuario"
  ["requirements.<scope>".composition]
  content = "content-planning-requirements"

["roles"]
generic = "generic-classic-document"

  ["roles".body]
  doc-title = "Documento de roles y actividades"
  ["roles".composition]
  content = "content-planning-roles"
