["specification"]
generic = "generic-classic-document"

  ["specification".body]
  doc-title = "Documento de especificación de pruebas"
  ["specification".composition]
  content = "content-testing-specification"
