["specification.<macrotarget>"]
template = "template-blank-document"

  ["specification.<macrotarget>".body]
  doc-title = "Documento de especificación de pruebas (<macrotarget>)"
  content = "content:testing-specification"
