# Templates
# ===
# The templates works also as generics
[template-blank-document]
filename = "template:blank-document"

  [template-blank-document.body]
  project-name = "<project-name>"

[template-changelog]
filename = "template:changelog"

[template-diagram-architecture]
filename = "template:diagram-architecture"

[template-database-diagram]
filename = "template:database-diagram"

[template-sofware-process]
filename = "template:sofware-process"

[template-sofware-sequence]
filename = "template:sofware-sequence"

[template-planning-schedule]
filename = "template:planning-schedule.mpp"

[template-environment-constants]
filename = "template:environment-constants"

[template-environment-credentials]
filename = "template:environment-credentials"

[template-environment-variables]
filename = "template:environment-variables"

[template-ui-constants]
filename = "template:ui-constants"

[template-ui-android-illustrator]
filename = "template:ui-android-illustrator.ai"

[template-ui-ios-illustrator]
filename = "template:ui-ios-illustrator.ai"

[template-ui-web-illustrator]
filename = "template:ui-web-illustrator.ai"
