# Generics
# ===
# The generics can be composited by traits(removed at moment).
# It is expected to have a body for fill variables
[generic-classic-document]
filename = "generic:mask-document"

  [generic-classic-document.body]
  project-name = "<project-name>"

# Raw Contents
# ===
# Are documents with only text.
# This is useful for composition with
# generic templates
[content-agreements-meeting-minutes]
filename = "content:agreements-meeting-minutes"

[content-database-spec]
filename = "content:database-spec"

[content-sofware-endpoints]
filename = "content:software-endpoints"

[content-closure-release-manual]
filename = "content:closure-release-manual"

[content-closure-technical-release]
filename = "content:closure-technical-release"

[content-planning-charter]
filename = "content:planning-charter"

[content-planning-requirements]
filename = "content:planning-requirements"

[content-planning-roles]
filename = "content:planning-roles"

[content-schedule-overview]
filename = "content:schedule-overview"

[content-testing-specification]
filename = "content:testing-specification"

# Templates
# ===
# The templates are only documents with static content.
# Doesn't allow to customize with variables
[template-changelog]
filename = "template:changelog"

[template-diagram-architecture]
filename = "template:diagram-architecture"

[template-database-diagram]
filename = "template:database-diagram"

[template-sofware-process]
filename = "template:sofware-process"

[template-sofware-sequence]
filename = "template:sofware-sequence"

[template-planning-schedule]
filename = "template:planning-schedule"

[template-environment-constants]
filename = "template:environment-constants"

[template-environment-credentials]
filename = "template:environment-credentials"

[template-environment-variables]
filename = "template:environment-variables"

[template-ui-constants]
filename = "template:ui-constants"

[template-ui-android-illustrator]
filename = "template:ui-android-illustrator"

[template-ui-ios-illustrator]
filename = "template:ui-ios-illustrator"

[template-ui-web-illustrator]
filename = "template:ui-web-illustrator"
