# This is the list for available apps
# Is useful for create new blank files

[g-docs]
name = "Google Docs"
category = "cloud"

[g-sheets]
name = "Google Sheets"
category = "cloud"

[draw-io]
name = "Draw.io"
category = "cloud"
