["CHANGELOG"]
template = "template-changelog"

["erd.<macrotarget>"]
template = "template-database-diagram"

["erd.<macrotarget>.spec"]
generic = "generic-classic-document"

  ["erd.<macrotarget>.spec".body]
  doc-title = "Documento de acta de reunión"
  content = "content-database-spec"
