["meeting-minutes"]
generic = "generic-classic-document"

  ["meeting-minutes".body]
  doc-title = "Documento de acta de reunión"
  ["meeting-minutes".composition]
  content = "content-agreements-meeting-minutes"
