["release-manual.<target>"]
generic = "generic-classic-document"

  ["release-manual.<target>".body]
  doc-title = "Manual de publicación del aplicativo <target>"
  ["release-manual.<target>".composition]
  content = "content-closure-release-manual"

["technical-release.<target>"]
generic = "generic-classic-document"

  ["technical-release.<target>".body]
  doc-title = "Informe técnico del aplicativo <target>"
  ["technical-release.<target>".composition]
  content = "content-closure-technical-release"
