["release-manual.<target>"]
template = "template-blank-document"

  ["release-manual.<target>".body]
  doc-title = "Manual de publicación del aplicativo <target>"
  content = "content:closure-release-manual"

["technical-release.<target>"]
template = "template-blank-document"

  ["technical-release.<target>".body]
  doc-title = "Informe técnico del aplicativo <target>"
  content = "content:closure-technical-release"
